# Site settings
title: "Robot Overlords, Reality, and Artificial Intelligence:"
title2: "The Philosophy of Science Fiction"
email: john.atytalla@philosophy.god
author: "John Atytalla"
description: "Reference website for a science-fiction and ai themed philosophy course."
baseurl: ""
url: "https://sci-fi-philosophy.github.io"
title_description: "Do you ever wonder whether computers could ever gain consciousness and take over the world? Could we be living in a computer simulation? Will brain implants fundamentally change the nature of who we are?
Science fiction is slowly becoming a reality.  Artificial intelligence is on the horizon, brain implants are real, and some scientists are even trying to upload our consciousness into computers. We will explore works of science fiction, in order to investigate how scientific knowledge comes to effect the personal lives of individuals living within the scientific age. In particular the course will engage in philosophical discussions about the ethical and personal implications of these emerging technologies. The future is now!"
title_image: "https://iiif.wellcomecollection.org/image/L0027293.jpg/full/800,/0/default.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
instagram_username:
reddit_username:
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <strong>John Atytalla</strong>, <small>design by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a></small>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
